"""Add audio_path to ebooks

Revision ID: 53d375359916
Revises: f3cbe5d9d024
Create Date: 2025-12-13 14:34:21.592533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d375359916'
down_revision = 'f3cbe5d9d024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebooks', schema=None) as batch_op:
        batch_op.drop_column('audio_path')

    # ### end Alembic commands ###
